// Generated by CoffeeScript 1.7.1
(function() {
  var Entity, f, global, is_entity, p, safe_get, safe_value, validate,
    __hasProp = {}.hasOwnProperty;

  if (typeof exports !== 'undefined') {
    global = exports;
    p = require('./predicates').vst.predicates;
    f = require('./functions').vst.functions;
  } else if (typeof window !== 'undefined') {
    global = window;
    p = window.vst.predicates;
    f = window.vst.functions;
  } else {
    global = this;
    p = this.vst.predicates;
    f = this.vst.functions;
  }

  safe_get = function(self, attr) {
    if (p.is_function(self[attr])) {
      return self[attr]();
    } else {
      return self[attr];
    }
  };

  safe_value = function(self, value) {
    if (p.is_function(value)) {
      return value.call(self);
    } else {
      return value;
    }
  };

  validate = function(value) {
    var element, k, v, _i, _len, _results, _results1;
    if (value instanceof Entity) {
      return value.validate();
    } else if (p.is_array(value)) {
      _results = [];
      for (_i = 0, _len = value.length; _i < _len; _i++) {
        element = value[_i];
        _results.push(validate(element));
      }
      return _results;
    } else if (p.is_object(value)) {
      _results1 = [];
      for (k in value) {
        if (!__hasProp.call(value, k)) continue;
        v = value[k];
        _results1.push(validate(v));
      }
      return _results1;
    } else {
      return true;
    }
  };

  Entity = (function() {
    Entity.def_property = function(ctor, property, _arg) {
      var field, get, init, initial_value, set, stringify;
      initial_value = _arg.initial_value, get = _arg.get, init = _arg.init, set = _arg.set, stringify = _arg.stringify;
      get || (get = function(field) {
        return this[field];
      });
      set || (set = function(field, value) {
        return this[field] = value;
      });
      if (set.length === 1) {
        set = (function(set) {
          return function(field, value) {
            return set(value);
          };
        })(set);
      }
      field = '__' + property;
      if (!p.is_undefined(initial_value)) {
        ctor.prototype[field] = initial_value;
      }
      ctor.__INITIALIZERS__ || (ctor.__INITIALIZERS__ = {});
      ctor.prototype[property] = function(value) {
        if (p.is_undefined(value)) {
          return this[field];
        } else {
          set.call(this, field, value);
          return this;
        }
      };
      if (stringify === false) {
        ctor.prototype[property].__STRINGIFY__ = false;
      }
      ctor.__PROPERTIES__ || (ctor.__PROPERTIES__ = []);
      ctor.__PROPERTIES__.push(property);
      ctor.properties || (ctor.properties = function() {
        var properties;
        return properties = p.is_function(ctor.__super__.properties) ? ctor.__super__.properties().concat(ctor.__PROPERTIES__) : ctor.__PROPERTIES__;
      });
      if (init) {
        ctor.__INITIALIZERS__[field] = init;
      }
      return true;
    };

    Entity.def_properties = function(ctor, properties) {
      var attrs, property, _results;
      _results = [];
      for (property in properties) {
        if (!__hasProp.call(properties, property)) continue;
        attrs = properties[property];
        _results.push(this.def_property(ctor, property, attrs));
      }
      return _results;
    };

    Entity.def_abstract_method = function(ctor, abstract_method, _arg) {
      var arity;
      arity = _arg.arity;
      ctor.__ABSTRACT_METHODS__ || (ctor.__ABSTRACT_METHODS__ = {});
      ctor.__ABSTRACT_METHODS__[abstract_method] = {};
      if (p.is_defined(arity)) {
        return ctor.__ABSTRACT_METHODS__[abstract_method].arity = arity;
      }
    };

    Entity.def_abstract_methods = function(ctor, abstract_methods) {
      var abstract_method, attrs, _results;
      _results = [];
      for (abstract_method in abstract_methods) {
        if (!__hasProp.call(abstract_methods, abstract_method)) continue;
        attrs = abstract_methods[abstract_method];
        _results.push(this.def_abstract_method(ctor, abstract_method, attrs));
      }
      return _results;
    };

    Entity.find_property = function(ctor, property) {
      if (p.is_function(ctor.prototype[property])) {
        return ctor.prototype[property];
      } else if (ctor.__super__ && is_entity(ctor.__super__.prototype)) {
        return this.find_property(ctor.__super__, property);
      } else {
        return null;
      }
    };

    Entity.def_toString = function(ctor, ctor_name) {
      var properties, property, property_name, _i, _len, _ref;
      ctor_name || (ctor_name = ctor.name);
      properties = [];
      _ref = ctor.properties();
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        property_name = _ref[_i];
        if (property = this.find_property(ctor, property_name)) {
          if (property.__STRINGIFY__ !== false) {
            properties.push(property_name);
          }
        }
      }
      ctor.prototype.toString = function() {
        var value, values, _j, _len1;
        values = [];
        for (_j = 0, _len1 = properties.length; _j < _len1; _j++) {
          property = properties[_j];
          value = safe_get(this, property);
          values.push(property + ': ' + f.to_string(value));
        }
        return "" + ctor_name + " {" + (values.join(', ')) + "}";
      };
      return true;
    };

    function Entity(subtypes) {
      var abstract_method, abstract_methods, attrs, field, init, subtype, type, _i, _len, _ref, _ref1;
      abstract_methods = {};
      for (_i = 0, _len = subtypes.length; _i < _len; _i++) {
        subtype = subtypes[_i];
        if (subtype !== undefined) {
          if (subtype.__ABSTRACT_METHODS__) {
            _ref = subtype.__ABSTRACT_METHODS__;
            for (abstract_method in _ref) {
              if (!__hasProp.call(_ref, abstract_method)) continue;
              attrs = _ref[abstract_method];
              abstract_method[abstract_method] = {
                type: subtype,
                attrs: attrs
              };
            }
          }
          _ref1 = subtype.__INITIALIZERS__;
          for (field in _ref1) {
            if (!__hasProp.call(_ref1, field)) continue;
            init = _ref1[field];
            this[field] = init.call(this, field);
          }
        }
      }
      type = subtypes[subtypes.length - 1];
      this.__TYPE__ = type;
    }

    Entity.prototype.equals = function(self, other) {
      var property, _i, _len, _ref;
      if (p.is_undefined(other)) {
        other = self;
        self = this;
      }
      if (is_entity(self)) {
        if (is_entity(other)) {
          _ref = self.constructor.properties();
          for (_i = 0, _len = _ref.length; _i < _len; _i++) {
            property = _ref[_i];
            if (!this.equals(self[property](), other[property]())) {
              return false;
            }
          }
          return true;
        } else {
          return false;
        }
      } else {
        return self === other;
      }
    };

    return Entity;

  })();

  is_entity = p.is_instance(Entity);

  global.vst || (global.vst = {});

  global.vst.Entity = Entity;

}).call(this);
