// Generated by CoffeeScript 1.7.1
(function() {
  var global, m, metrics;

  global = typeof exports !== void 0 ? exports : typeof window !== void 0 ? window : this;

  m = metrics = {
    m_number: function(a, b) {
      if (a.key() < b.key()) {
        return a.key() - b.key();
      } else {
        return b.key() - a.key();
      }
    }
  };

  global.vst || (global.vst = {});

  global.vst.metrics = metrics;

}).call(this);
