// Generated by CoffeeScript 1.7.1
(function() {
  var global, m, metrics;

  global = typeof exports !== 'undefined' ? exports : typeof window !== 'undefined' ? window : this;

  m = metrics = {
    m_number: function(a, b) {
      return Math.abs(a.key() - b.key());
    }
  };

  global.vst || (global.vst = {});

  global.vst.metrics = metrics;

}).call(this);
